# SPDX-License-Identifier: Apache-2.0
name: "306: [FLOW] Snyk Monitor"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  extract-jdk-version:
    name: Extract Java Version
    uses: ./.github/workflows/854-call-extract-jdk-version.yaml
    with:
      ref: ${{ github.ref }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  snyk:
    name: Snyk Monitor
    needs:
      - extract-jdk-version
    runs-on: hl-cn-snyk-check-lin

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Prepare Runner
        id: prepare-runner
        uses: pandaswhocode/initialize-github-job@5dbfbc4329ceab48a57d983325dadbd3ec8123e9 # v1.2.2
        with:
          checkout: "true"
          checkout-fetch-depth: "1"
          checkout-token: "${{ secrets.GITHUB_TOKEN }}"
          setup-java: "true"
          java-distribution: "temurin"
          java-version: "${{ needs.extract-jdk-version.outputs.jdk-version }}"
          setup-gradle: "true"
          setup-node: "true"
          node-version: "20"

      - name: Compile
        run: ./gradlew assemble

      - name: Setup Snyk
        uses: step-security/snyk-actions/setup@3ccbd440152e3235d4b9d631c16badbc85807eca # v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Disable Gradle Isolated Projects
        run: sed -i 's/^org.gradle.unsafe.isolated-projects=.*$/org.gradle.unsafe.isolated-projects=false/' gradle.properties

      - name: Run Snyk Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --subProject=aggregation --configuration-matching=mainRuntimeClasspath --policy-path=.snyk --trust-policies --org=hiero-consensus-node
