# SPDX-License-Identifier: Apache-2.0
name: "701: [FLOW] Auto Unapprove PR"
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-unapprove:
    name: Auto Unapprove PR
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Initialize Job
        uses: pandaswhocode/initialize-github-job@5dbfbc4329ceab48a57d983325dadbd3ec8123e9 # v1.2.2
        with:
          checkout: "true"
          checkout-token: "${{ secrets.GITHUB_TOKEN }}"
          setup-node: "true"
          node-version: "20"

      - name: Dismiss Reviews from Code Owners and Teams
        uses: step-security/auto-unapprove@c87029c4f62d004fb8979a7a5cb90b3c1729df32 # v1.0.3
        with:
          github-token: ${{ secrets.GH_AUTO_UNAPPROVE_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          dry-run: "false"
          code-owners-file: ".github/CODEOWNERS"
          target-branch: ${{ github.event.pull_request.base.ref }}
          team-start-with: "@hiero-ledger/"
