# SPDX-License-Identifier: Apache-2.0
name: "857: [CALL] Workflow Unit Tests"
on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test-gomplate-templates:
    name: Validate Gomplate Templates
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Initialize GitHub Job
        uses: pandaswhocode/initialize-github-job@5dbfbc4329ceab48a57d983325dadbd3ec8123e9 # v1.2.2
        with:
          checkout: "true"
          checkout-ref: "${{ needs.fetch-xts-candidate.outputs.xts-tag-commit }}"
          checkout-token: "${{ secrets.GITHUB_TOKEN }}"
          setup-gomplate: "true"

      - name: Test Templates
        run: bash ./.github/workflows/support/tests/test-gomplate-templates.sh
