# SPDX-License-Identifier: Apache-2.0
name: "Deprecated: [CITR] MATS Dry Run"
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  print-deprecated:
    name: Print Deprecated Warning
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Print Deprecation Warning
        run: |
          echo "::warning::This workflow is deprecated and will be removed in a future release."
          exit 1
