# SPDX-License-Identifier: Apache-2.0
name: "Deprecated: ZXC: [Node] Deploy Release Artifacts"
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  print-deprecated:
    name: Print Deprecated Warning
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: Print Deprecation Warning
        run: |
          echo "::warning::This workflow is deprecated and will be removed in a future release."
          exit 1
