# SPDX-License-Identifier: Apache-2.0
name: "Deprecated: ZXC: Verify Gradle Build Determinism"
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  print-deprecated:
    name: Print Deprecated Warning
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Print Deprecation Warning
        run: |
          echo "::warning::This workflow is deprecated and will be removed in a future release."
          exit 1
