# SPDX-License-Identifier: Apache-2.0
name: "Deprecated: ZXC: [CITR] Execute Performance Test"
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  print-deprecated:
    name: Print Deprecated Warning
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Print Deprecation Warning
        run: |
          echo "::warning::This workflow is deprecated and will be removed in a future release."
          exit 1
